import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import MainNav from "@/app/components/MainNav/MainNav";
import StyledComponentsRegistry from './lib/registry'

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="en">
    <head></head>
    <body className={inter.className}>
    <StyledComponentsRegistry>
      <MainNav/>
      {children}
    </StyledComponentsRegistry>
    </body>
    </html>
  );
}
